image: python:3.10.1

variables:
  TESTING:${TESTING}
  DB_URL:${DB_URL}
  DB_TEST_URL:${DB_TEST_URL}
  SECRET_KEY:${SECRET_KEY}
  ALGORITHM:${ALGORITHM}
  ACCESS_TOKEN_EXPIRE_MINUTES:${ACCESS_TOKEN_EXPIRE_MINUTES}
  POSTGRES_USER:${POSTGRES_USER}
  POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
  POSTGRES_DB:${POSTGRES_DB}
  POSTGRES_TEST_DB:${POSTGRES_TEST_DB}
  POSTGRES_TEST_USER:${POSTGRES_TEST_USER}
  POSTGRES_TEST_PASSWORD:${POSTGRES_TEST_PASSWORD}

stages:
  - test

before_script:
  - python --version  # For debugging
  - pip install docker-compose

test:
  script:
    - docker-compose run app sh -c "TESTING=True pytest app && flake8 app"

